# Site settings
title: My Research Group
description: Welcome to My Research Group - A minimal homepage for testing purposes
baseurl: "/members_yaml" # the subpath of your site, e.g., /blog/
url: "https://javierdomcal.github.io" # the base hostname & protocol for your site


# Build settings
theme: minima
markdown: kramdown
plugins:
  - jekyll-feed

# Permalinks
permalink: pretty

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
